name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Build your project here (if needed)

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          branch: gh-pages
          name: github-pages  # Specify the artifact name
          path: .  # Specify the path to your generated files

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: github-pages  # Match the artifact name from the upload step

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: .  # Path to the directory containing your static HTML file
          artifact_name: github-pages  # Specify the artifact name to deploy
